### ISSUE TITLE
BUILDER> Playground> "Go to intent's item" is not working 

### ISSUE THREAD

**Issue by ghost** [Opla/opla#109]
CURRENTLY  : 
In the playgroung when you click on "go to intent's item" in order to modify an input or an output quickly, user is not redirected to the correct intent (click doesn't seem to go anywhere)
<img width="470" alt="capture d ecran 2018-11-08 a 10 21 29" src="https://user-images.githubusercontent.com/39262841/48189507-aaeef800-e340-11e8-8838-4bae4a7a3816.png">

SHOULD ACTUALLY BE : 
Click on "go to intent's item" should redirect to the right intent

**Comment by jeffladiray** [comment]
Goto intent work since #109. Closing this one
