### ISSUE TITLE
BUILDER> Text editor> Hard to enter in text editor

### ISSUE THREAD

**Issue by ghost** [Opla/opla#111]
CURRENTLY = 
When entering a new text field it's really hard to be able to edit it
https://youtu.be/rtEJKKRSyjQ
You have to cancel your action, get out of the editor window and come back to actually be able to edit it

SHOULD ACTUALLY BE : 
When clicking in the text editor you should be able to edit it directly

**Comment by mikbry** [comment]
Fixed ?

**Comment by arnaud-moncel** [comment]
yes
