### ISSUE TITLE
BUILDER> Editing bar> Random display complicating editing

### ISSUE THREAD

**Issue by julieopla** [Opla/opla#112]
CURRENTLY : 
https://youtu.be/rTq0FkG4wAE
Editing bar disappears when you're editing text. It scrolls randomly and when you fold back the output / input list the bar stays in.

ACTUALLY SHOULD BE : 
Editing bar should stay in when editing (even text) and disappear only when out of the editing fields.

**Comment by lodelestra** [comment]
duplicate #25
