### ISSUE TITLE
e2e test fails to create webchat connector plugin

### ISSUE THREAD

**Issue by licarth** [Opla/opla#129]
**Describe the bug**
e2e test cannot create webchat-connector plugin. My guess is that the e2e test framework clicks on 'ADD' quickly and it's a problem because page is not fully loaded.
See e2e test failing since commit [d082a98cb563fe742d317f5529151d0ff84efe97](https://github.com/Opla/opla/commit/d082a98cb563fe742d317f5529151d0ff84efe97) 
See video here : https://circleci.com/workflow-run/8a7e32ed-5a89-4c50-bf0d-35ab11381c07

**To Reproduce**
Run e2e test.

**Expected behavior**
The fact that the user clicks on the button quickly should not make the whole thing fail (e.g. slow internet connections). Window should be functional.

**Screenshots**
![image](https://user-images.githubusercontent.com/5550241/48985040-99904480-f0d1-11e8-9779-f9b84793381d.png)

**Comment by lodelestra** [comment]
It doesnt failed on during PR tests. I dont understand why cypress_e2e is ok and qa_e2e fail.
I will revert this PR for now.

**Comment by licarth** [comment]
Update: I committed https://github.com/Opla/opla/pull/130 as a stopgap measure.
