### ISSUE TITLE
Publish doesn't work

### ISSUE THREAD

**Issue by E1000y** [Opla/opla#137]
OS : windows 10 home, browser : chrome Version 70.0.3538.110 (Build officiel) (64 bits)

When trying to press publish button in Chatbot dashboard, nothing happens, and under inspect this error appears :
![issue_publish](https://user-images.githubusercontent.com/45007116/49438176-d806bd00-f7bd-11e8-908a-d6c12bb40776.png)

**Comment by mikbry** [comment]
To make it works you need to follow these steps:
- go to admin screen
- select extensions tab
- click add button on messaging platforms
- select webchat-connector
- done
- go back to factory screen
- in Dashboard under Publish to : activate webchat-connector
Now Publish button is working

Right we need to simply the process and make it works smoothly...

**Comment by mikbry** [comment]
Fixed ?

**Comment by E1000y** [comment]
Yes because everything is now on the same pane. And seems to work.
