### ISSUE TITLE
Builder : Global variables

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#150]
**Describe.**
An entry to add/modify variables to a particular assistant

**How it works**
Display an entry "Variables" in builder explorer, with a sub item called "&Global"
![screenshot 2018-12-21 at 09 35 42](https://user-images.githubusercontent.com/395718/50332999-23ca9d80-0504-11e9-9b88-2fab8f88a825.png)
When this item is selected, it will display a table with all keys/values associated to an assistant. With these actions: add / edit / delete

**Comment by mikbry** [comment]
Variables are displayed in a MD table, for design see:
https://material.io/design/components/data-tables.html#

columns are:
| name | value | default value | type | access | description |

where 
name : is the name of the variable
value : is the current value of the variable (or default value)
Display value or default value
type : type of the variable (string or number at first)
access : read or read/write
description : an informative field
 
We could add/delete/edit a row

**Comment by arnaud-moncel** [comment]
done with #249
