### ISSUE TITLE
Blank page at start

### ISSUE THREAD

**Issue by E1000y** [Opla/opla#164]
**Describe the bug**
blank page at start

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Microsoft windows 10 famille
 - Browser chrome
 - Version Version 71.0.3578.98 (Build officiel) (64 bits)

**Comment by mikbry** [comment]
<img width="539" alt="screenshot 2019-01-22 at 11 53 31" src="https://user-images.githubusercontent.com/395718/51530964-6bfb1980-1e3c-11e9-9e18-9f8d7033c4a2.png">

There is a bug in index line 40, it throws an error:
`Cannot read property of mainColor of indefined`
