### ISSUE TITLE
simplify publish

### ISSUE THREAD

**Issue by E1000y** [Opla/opla#203]
I would like the webchat connector to be default implemented when publishing bots from the Builder. 
As a user, today, I need to go to the extensions board to select webchat and it's time consuming and confusing. Maybe consider getting rid of the extensions board? and maybe ask whether bot should be published in webchat or in fb messenger via a pop-up while clicking on publish? Or default use webchat when publishing.

**Comment by arnaud-moncel** [comment]
Related to #219 ?

**Comment by mikbry** [comment]
It could be

**Comment by E1000y** [comment]
yes
