### ISSUE TITLE
bot timezone is save as varchar, profile timezone as int

### ISSUE THREAD

**Issue by jeffladiray** [Opla/opla#210]
**Describe the bug**
Timezone is not always saved with the same property type
`Profiles.timezone` is an `int(10)` and is always NULL
`Bots.timezone` is an `varchar(40)` and saved as a "location"

**Expected behavior**
Both of the field should be saved. We need a `timezone_location` and a `timezone_offset` in order to calculate correct UTC dates

**Additional context**
Related to #199

**Comment by arnaud-moncel** [comment]
I think it should be fine like this. The toLocalString Date function take [IANA time zone notation](https://www.iana.org/time-zones).
```js
new Date().toLocaleString("en", { timeZone: "Europe/Paris" });
```
