### ISSUE TITLE
Feature : factory change tabs and design

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#219]
**Is your feature request related to a problem? Please describe.**
Factory Dashboard, Builder and analytics are not effective

**Describe the solution you'd like**
- Remove extensions as in #216 
- Rename dashboard to settings and put it at the end
- Put analytics screen in new dashboard at first
![screenshot 2019-03-08 at 16 13 10](https://user-images.githubusercontent.com/395718/54037097-a1c24a80-41bd-11e9-94ce-378f45c46146.png)

In settings tab:
- put "Publish to" in an expansion pane (add button)
- add "Web service" in an expansion pane (add button)
- put description + language + localize + timezone in a Properties expansion pane (save button)
- import/export + duplicate + delete put it in a menu at the top right corner
![screenshot 2019-03-08 at 16 22 14](https://user-images.githubusercontent.com/395718/54037604-d7b3fe80-41be-11e9-9e80-43b8f132e274.png)
Redesign everything before starting

**Comment by damien-citaire** [comment]
I made these 2 mockup based on the indications provided

![_Dashboard](https://user-images.githubusercontent.com/22832527/54609148-a5be5a00-4a52-11e9-8083-bfb3d233bc7b.jpg)

![_Settings](https://user-images.githubusercontent.com/22832527/54609135-9d661f00-4a52-11e9-89c5-5cfc8118be64.jpg)

**Comment by mikbry** [comment]
"Save bot configuration" in menu could be removed as it is present in Properties.
Also Add or Save buttons could be same as in an expansion panel, in a bottom bar see:
https://material-ui.com/demos/expansion-panels/
