### ISSUE TITLE
Factory settings : Put bot's parameters in an expansion panel

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#238]
In latest version
![Screenshot 2019-03-27 at 13 14 52](https://user-images.githubusercontent.com/395718/55075104-5e5b4d80-5092-11e9-9923-ca3de4b5c426.png)

**Describe the solution you'd like**
Put all Bot's parameters (description, language, timezone) in an expansion panel called Parameters. And by default don't expand it.

**Comment by damien-citaire** [comment]
Move parameters in expansion panel cause overflow issue with timezone menu, this is why we let him outside panel.
