### ISSUE TITLE
Admin : advanced error and nothing displayed

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#239]
**Describe the bug**
Admin/advanced display nothing nothing only an error

**To Reproduce**
1. Go to Admin
2. Click on advanced
3. See error

**Expected behavior**
Should display advanced settings when your are an admin.

**Screenshots**
![Screenshot 2019-03-27 at 14 45 32](https://user-images.githubusercontent.com/395718/55081060-738aa900-509f-11e9-9ac3-a5244b7dc642.png)
On backend
![Screenshot 2019-03-27 at 14 49 41](https://user-images.githubusercontent.com/395718/55081125-9321d180-509f-11e9-9443-8d2644220668.png)

**Version**
Latest version on local instance

**Comment by arnaud-moncel** [comment]
Cant reproduce on my local & on qa.

**Comment by mikbry** [comment]
Could be when no parameters are set for email server ?

**Comment by arnaud-moncel** [comment]
I think no, no email parameters are set on qa. Maybe your local DB has invalid data or something like this?
