### ISSUE TITLE
Json Webservice connexion 

### ISSUE THREAD

**Issue by kyusolution** [Opla/opla#244]
**Describe the bug**
When adding a webservice to a bot, the connection is not established. A restart is required

**To Reproduce**
1. Create a new bot
2. Import intents
3. Add a new json webservice 
4. Test in the playground : no response

**Expected behavior**
The data from the webservice must be displayed

**Comment by jeffladiray** [comment]
Rel. to https://github.com/Opla/opla/issues/235
