### ISSUE TITLE
mailto for e-mails appearing in webchat

### ISSUE THREAD

**Issue by E1000y** [Opla/opla#245]
**Is your feature request related to a problem? Please describe.**
When showing an e-mail address, we need to make it clickable and it needs to open a mailto the like of Outlook mailto.

**Describe the solution you'd like**
when I click an e-mail in the webchat, I want it to redirect me to a mail window with it in send parameters.

**Comment by jeffladiray** [comment]
Mailto already work on QA.

Just use markdown syntax to make it work

```
The response [MailMe](mailto:test@example.com) 
```
