### ISSUE TITLE
Connected> Profile icon, arrow not functionnal

### ISSUE THREAD

**Issue by julieopla** [Opla/opla#27]
CURRENTLY
The arrow next to the profile icon is not working
<img width="168" alt="capture d ecran 2018-08-21 a 11 01 19" src="https://user-images.githubusercontent.com/39262841/44473431-88e2b500-a630-11e8-926b-dc19b1876068.png">

SHOULD BE 
This arrow should develop the user menu just like when you type directly on the icon
<img width="238" alt="capture d ecran 2018-08-22 a 17 26 54" src="https://user-images.githubusercontent.com/39262841/44473459-9b5cee80-a630-11e8-9884-f49757814298.png">

**Comment by mikbry** [comment]
Fixed in last PR
