### ISSUE TITLE
Factory > "Save" button doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [Opla/opla#28]
CURRENTLY 
When you click the "Save" Button on the admin section, the modification made doesn't seem to be saved when you come back on the section
<img width="1436" alt="capture d ecran 2018-08-22 a 17 28 20" src="https://user-images.githubusercontent.com/39262841/44473631-03133980-a631-11e8-9ad9-873cd21c6cd3.png">
<img width="1434" alt="capture d ecran 2018-08-22 a 17 28 26" src="https://user-images.githubusercontent.com/39262841/44473632-03abd000-a631-11e8-9b9e-ef0fe2d2ddb0.png">

SHOULD BE
First of all when clicking on the save button a confirmation message should be displayed + the modifications should be saved

**Comment by julieopla** [comment]
https://github.com/Opla/opla/issues/11

**Comment by lodelestra** [comment]
This issue is impacted by #73 , please do not fix before #73 merge.
