### ISSUE TITLE
Builder > Playground> "go to intent's name" doesn't work

### ISSUE THREAD

**Issue by julieopla** [Opla/opla#30]
CURRENTLY
Trying to reach the right intent directly from the playground doesn't redirect 
<img width="1440" alt="capture d ecran 2018-08-21 a 11 01 57" src="https://user-images.githubusercontent.com/39262841/44474069-0955e580-a632-11e8-8afd-8efd84ec45f9.png">

SHOULD BE
Should redirect to the right intent in order to modify it

**Comment by arnaud-moncel** [comment]
duplicate #109
