### ISSUE TITLE
Builder> variable> added variable in input.output appears in the playground

### ISSUE THREAD

**Issue by ghost** [Opla/opla#33]
CURRENTLY
when adding a variable in the builder it appears in the sentence in the playground
<img width="1440" alt="capture d ecran 2018-08-22 a 15 44 47" src="https://user-images.githubusercontent.com/39262841/44474490-11625500-a633-11e8-9872-0bc69ed5f09a.png">

SHOULD BE
Variable should be invisible

**Comment by mikbry** [comment]
Should be fixed
