### ISSUE TITLE
Builder> Examples disturb administration, has to be deleted

### ISSUE THREAD

**Issue by ghost** [Opla/opla#34]
CURRENTLY 
When creating an intent, in input / output, examples are displayed (Intent / I don't understand). They don't disappear when you start administrating your intent so you have to delete them everytime.
+ if you don't delete the example in the output section you are not able to add a condition on the output
<img width="722" alt="capture d ecran 2018-08-22 a 17 47 12" src="https://user-images.githubusercontent.com/39262841/44474704-96e60500-a633-11e8-9c87-e92064dd5bb4.png">

SHOULD BE
Either : 
- delete the examples
- make them disappear automatically when the administration has started
- try to find something else to show that there is a field for creating and one for modifying existing content

**Comment by jeffladiray** [comment]
Solution choosed:

First intent created will contains both `input: Hello` and `output: I don't understand`.  Any other intent created after this one will be empty, in order to show conditionnal capability
