### ISSUE TITLE
Playground welcome message editing ghost

### ISSUE THREAD

**Issue by lodelestra** [Opla/opla#56]
Opla CE - PREPROD
v0.1.0 - b:ci.766 c:95d2aea d:10.09.18 15:24

On save, the old message is display again, but updated in the playground
<img width="867" alt="screen shot 2018-09-25 at 15 48 18" src="https://user-images.githubusercontent.com/10141712/46019312-19069500-c0dc-11e8-8000-af05a5877c67.png">

<img width="909" alt="screen shot 2018-09-25 at 15 49 54" src="https://user-images.githubusercontent.com/10141712/46019277-012f1100-c0dc-11e8-8525-2201e119f504.png">

<img width="1199" alt="screen shot 2018-09-25 at 15 50 35" src="https://user-images.githubusercontent.com/10141712/46019262-f5434f00-c0db-11e8-9c98-943c1faf6f12.png">

**Comment by mikbry** [comment]
Can't reproduce it
