### ISSUE TITLE
Admin extensions list display

### ISSUE THREAD

**Issue by lodelestra** [Opla/opla#57]
Extensions lists are not always displayed, even if multiple extensions are activated in builder publish.

<img width="1659" alt="screen shot 2018-10-02 at 12 16 52" src="https://user-images.githubusercontent.com/10141712/46343218-5b305900-c63d-11e8-81b8-859fe3d974ec.png">

<img width="737" alt="screen shot 2018-10-02 at 12 19 27" src="https://user-images.githubusercontent.com/10141712/46343244-71d6b000-c63d-11e8-8cec-7f01588b2d60.png">

**Comment by mikbry** [comment]
Should be related to some e2e tests, when network is very slow, backend returned plugins list is not available

**Comment by mikbry** [comment]
Extensions are not present in admin anymore
