### ISSUE TITLE
bug: fix handling of language codeblocks copied to clipboard.

### ISSUE THREAD

**Issue by kustomzone** [Opla/opla#674]
Hi mik, thanks for your efforts! Will join Discord once link is posted.

**Describe the bug**
Currently code copied to clipboard is outputting: '[object object], { ,[object object], } . . . '

**To Reproduce**
Testing on Win10.
Text or Bash are fine, but JS or Python are borked.

**Expected behavior**
Source code languages could be handled on a per case basis, like math or mermaid are already.

**Temp Fix**
Not worth making a PR as there's likely a more elegant way to handle languages already planned.
Code output assists this and other projects so.. temp fix.

In 'opla\webapp\components\common\Markdown\CodeBlock.tsx'.

Line 73: `navigator.clipboard.writeText(children?.toString() ?? '');`

Replace with:
`if (display === 'python' || display === 'javascript') {
   const codecopy = ref.current.innerText;
   navigator.clipboard.writeText(codecopy);
 } else if (display === 'bash' || display === '') {
   const textcopy = children?.toString() ?? '';
   navigator.clipboard.writeText(textcopy);
 }`
 
Above this, add languages as necessary:
 `    } else if (language === 'bash') {
        display = 'bash';
    } else if (language === 'python') {
        display = 'python';
    } else if (language === 'javascript') {
        display = 'javascript';
    }`
   
And then adding same in code block below:
`  {display === '' && children}
   {display === 'bash' && children}
   {display === 'python' && children}
   {display === 'javascript' && children}
`

Seems to work fine.

**Comment by mikbry** [comment]
Thanks @kustomzone for your report. I fix this ASAP. And yes I need to change the discord invitation link.

**Comment by kustomzone** [comment]
Was overthinking it after seeing the Latex and Mermaid examples and imagining possible output types and languages.

Replacing line 73 with: `navigator.clipboard.writeText(ref.current.innerText);` ..works in all (?) cases.
Just need to bypass any handled separately: `{display !== 'latex' && display !== 'mermaid'  && children}`

**Comment by mikbry** [comment]
@kustomzone I took a slighty different approch, by getting the code from the markdown content. Same for the language. I did that, because time to time the language was not detected correctly using classname.
If you want to review the PR, i will be delighted.
