### ISSUE TITLE
bug: code copied from an indented list in an assistant message is not well indented

### ISSUE THREAD

**Issue by mikbry** [Opla/opla#707]
There is an extra indendation in code copied inside a list:

![Image](https://github.com/Opla/opla/assets/395718/a36d8f7a-e8e8-45d1-9682-2eb97e39bb97)

Example message:
======
4. Run your Tauri app:
   ```bash
   tauri dev
   ```

------

   tauri dev

------

1. Install the `react-devtools` package:
   ```bash
   npm install react-devtools --save-dev
   ```
   or if you are using Yarn:
   ```bash
   yarn add react-devtools --dev
   ```

2. Add the following import statement at the top of your React component file:
   ```javascript
   import { DevTools } from 'react-devtools';
   ```

3. Include the `DevTools` component in your app's root component, typically within the `render()` method or using a functional component:

   ```javascript
   // For class components
   render() {
     return (
       <div>
         {/* Your existing app content */}
         <DevTools />
       </div>
     );
   }
   
   // For functional components with React.StrictMode
   import React from 'react';
   import ReactDOM from 'react-dom';
   import App from './App';
   import './index.css';

   ReactDOM.render(
     <React.StrictMode>
       <DevTools />
       <App />
     </React.StrictMode>,
     document.getElementById('root')
   );
   ```

------

Not correct (all indented)

   npm install react-devtools --save-dev

------

   yarn add react-devtools --dev

------

   import { DevTools } from 'react-devtools';

------

   // For class components
   render() {
     return (
       <div>
         {/* Your existing app content */}
         <DevTools />
       </div>
     );
   }
   
   // For functional components with React.StrictMode
   import React from 'react';
   import ReactDOM from 'react-dom';
   import App from './App';
   import './index.css';

   ReactDOM.render(
     <React.StrictMode>
       <DevTools />
       <App />
     </React.StrictMode>,
     document.getElementById('root')
   );

------

Working correctly (not indented) 

```javascript
import React, { useCallback } from 'react';
import { clipboard } from '@tauri-apps/api/clipboard';

const CodeCopyButton = ({ code }) => {
  const handleCopyCode = useCallback(async () => {
    try {
      await clipboard.writeText(code, { mimeType: 'application/x-python' });
      alert('Code copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy code:', error);
      alert('Failed to copy code.');
    }
  }, [code]);

  return (
    <button onClick={handleCopyCode}>
      Copy Code
    </button>
  );
};

export default CodeCopyButton;
```

------

import React, { useCallback } from 'react';
import { clipboard } from '@tauri-apps/api/clipboard';

const CodeCopyButton = ({ code }) => {
  const handleCopyCode = useCallback(async () => {
    try {
      await clipboard.writeText(code, { mimeType: 'application/x-python' });
      alert('Code copied to clipboard!');
    } catch (error) {
      console.error('Failed to copy code:', error);
      alert('Failed to copy code.');
    }
  }, [code]);

  return (
    <button onClick={handleCopyCode}>
      Copy Code
    </button>
  );
};

export default CodeCopyButton;

======

**Comment by kustomzone** [comment]
To be clear, it indents to the same depth as the displayed (html) codeblock. So when it has code inside a subset list of a list it is double indented.  ie.  4.1 [code]  ..will have 6 spaces of indent per line.   4. [code]  ..will have 3.

**Comment by mikbry** [comment]
Yes, I found a simple solution for that. See my associated PR
