### ISSUE TITLE
[CLIENT CLAIM] Priority + / Builder> Make links openable in blank

### ISSUE THREAD

**Issue by ghost** [Opla/opla#85]
CURRENTLY IS
There is no possibility to insert a link within a conversation. 
By the way, when slashes are written in Builder they disappear in the webchat

(Insert link is in TODO)
<img width="465" alt="capture d ecran 2018-11-06 a 17 52 06" src="https://user-images.githubusercontent.com/39262841/48079886-a44f6c00-e1ec-11e8-870b-a729fc623db1.png">
<img width="601" alt="capture d ecran 2018-11-06 a 17 56 36" src="https://user-images.githubusercontent.com/39262841/48080114-3c4d5580-e1ed-11e8-8c39-40943b65aa7c.png">

(Slashes disappear in webchat)
<img width="539" alt="capture d ecran 2018-11-06 a 17 53 23" src="https://user-images.githubusercontent.com/39262841/48079968-d9f45500-e1ec-11e8-8b43-d064a72c2b56.png">

SHOULD ACTUALLY BE
These links should be openable in blank and appear behind a label

**Comment by julieopla** [comment]
Ok links work but labels have to be in one single attached word
How to put group of words as a label with the methodology "http://url.com|label in a few words" ?

<img width="424" alt="capture d ecran 2018-11-16 a 17 56 41" src="https://user-images.githubusercontent.com/39262841/48635539-be493580-e9c8-11e8-8ddc-24c1544fee7c.png">

**Comment by mikbry** [comment]
Easy replace all spaces with the html entity : `&#160;`

**Comment by arnaud-moncel** [comment]
fixed by e6d09fee66b6ed68d98062f014445d307947f43b
