### ISSUE TITLE
BUILDER> any in inputs are not working 

### ISSUE THREAD

**Issue by ghost** [Opla/opla#86]
CURRENTLY
There seems to be a problem with "any" inputs these days.
Inputs added with a "any" condition doesn't work : 
<img width="1152" alt="capture d ecran 2018-11-06 a 18 01 35" src="https://user-images.githubusercontent.com/39262841/48080486-12e0f980-e1ee-11e8-9206-cfc16d724058.png">
<img width="1161" alt="capture d ecran 2018-11-06 a 18 01 04" src="https://user-images.githubusercontent.com/39262841/48080487-12e0f980-e1ee-11e8-9a2d-ea8b7ace269c.png">
(I have other examples if needed)

SHOULD BE
In this example : 
<img width="1152" alt="capture d ecran 2018-11-06 a 18 01 35" src="https://user-images.githubusercontent.com/39262841/48080536-29875080-e1ee-11e8-94a7-2a50541877ea.png">
"any Github" in Input should bring the corresponding output

**Comment by arnaud-moncel** [comment]
I think it's working.
